// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anncgphspfjvrhwphscb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubmNncGhzcGZqdnJod3Boc2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDEzNDUsImV4cCI6MjA2NTQxNzM0NX0.N2iVok4m5qM10LgzEoe2WrUZv9cgRfuA-GeEq-Nrqto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);